# Generated by Django 2.2.9 on 2020-03-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('companylocation', models.CharField(max_length=255)),
                ('companydescription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'companytypes',
                'db_table': 'companytype',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=255)),
                ('employeeposition', models.CharField(max_length=255)),
                ('employeecompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateapp.Company')),
            ],
            options={
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='RatingNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingnum', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'ratingnumbers',
                'db_table': 'ratingnumber',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewdescription', models.TextField()),
                ('reviewcompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateapp.Company')),
                ('reviewemployee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateapp.Employee')),
                ('reviewrating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateapp.RatingNumber')),
                ('reviewuser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='companytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rateapp.CompanyType'),
        ),
    ]
